routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/', 'SiteController@index');
// Route::get('/contact-us', 'SiteController@contactUs')->name('contactUs');
// Route::get('/terms', 'SiteController@terms')->name('terms');
// Route::get('/privacy-policy', 'SiteController@privacyPolicy')->name('privacyPolicy');
// Route::get('/payment-refund-policy', 'SiteController@paymentRefundPolicy')->name('paymentRefundPolicy');
// Route::get('/disclaimer', 'SiteController@disclaimer')->name('disclaimer');

Auth::routes(['verify' => true]);

//Route::middleware(['verified', 'auth'])->get('/home', 'HomeController@index')->name('home');
Route::get('/start', 'HomeController@start')->name('start');
Route::any('/ajax-register', 'HomeController@createAccountAjax');
Route::post('/ajax-register-otp', 'HomeController@createAccountAjaxOTP');
Route::post('/ajax-car-makes', 'HomeController@getCarMakes')->name('ajaxGetCarMakes');
Route::post('/ajax-car-models', 'HomeController@getCarModels')->name('ajaxGetCarModels');
Route::post('/ajax-car-variants', 'HomeController@getCarVariants')->name('ajaxGetCarVariants');
Route::post('/ajax-car-values', 'HomeController@getCarValues')->name('ajaxGetCarValues');
Route::post('/ajax-save-car-leads', 'HomeController@saveCarLeads')->name('ajaxSaveCarLeads');
Route::post('/ajax-save-more-about-me', 'HomeController@saveMoreAboutMe')->name('ajaxSaveMoreAboutMe');
Route::post('/ajax-save-renewal-details', 'HomeController@saveRenewalDetails')->name('ajaxSaveRenewalDetails');
Route::post('/ajax-filter-detail', 'HomeController@getFilterResult')->name('ajaxGetFilterResult');
Route::get('/reset-password/{token}', 'UserController@resetPassword')->name('resetPassword');
Route::post('/reset-password-save','UserController@resetPasswordSave')->name('resetPasswordSave');

//premium policy page route
Route::get('/premiumplans', 'HomeController@getPremium')->name('premium');

//Route::post('ajaxGetData/{$page}','AdminCarMakeController@ajaxGetDatas');


Route::prefix('admin')->name('admin.')->group(function() {
    // Admin Auth
    Route::get('/', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login')->name('login.submit');
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('logout');
    // 
    // 
    Route::middleware(['role:super-admin|sub-admin'])->group(function () {
        //
        Route::get('/home', 'AdminController@index')->name('home');

        // Cars
        Route::post('/cars/make/models','AdminCarController@getCarMakeModels')->name('getCarMakeModels');
        Route::post('/cars/body_type/variants','AdminCarController@getVariantByBodyType')->name('getVariantByBodyType');
        // car section 
        Route::resource('/car','AdminCarController');
        Route::resource('/cars/car-makes','AdminCarMakeController');
        Route::resource('/cars/car-models','AdminCarModelController');
        Route::resource('/cars/car-model-variants','AdminCarModelVariantController');
        Route::resource('/cars/car-model-body','AdminCarModelBodyController');
        Route::resource('/cars/car-model-fuel','AdminCarModelFuelController');
        // 
        Route::post('/cars/car-body-keyword-exist','AdminCarModelBodyController@keywordExist')->name('carModelBodyKeywordExist');
        //partners 
        Route::resource('/partners/premium-plans','AdminCarPremiumController');
        Route::resource('/partners/third-party-covers','AdminThirdPartyCoverController');
        Route::resource('/partners/benefit-masters','AdminBenefitMasterController');
        Route::resource('/partners','AdminInsuranceProviderController');
        //
        Route::resource('/planbenefits','AdminPlanBenefitController');
        // 
        Route::resource('/excess','AdminExcessController');
        Route::resource('/cross-selling-products','AdminCrossSellingProductsController');
        //
        Route::resource('/homepages','HomepageController');
        // site users
        Route::resource('/users','AdminUserController');
        Route::get('/users/show/{id}','AdminUserController@show')->name('users.view');
        Route::get('/user/{user_id}/orders','AdminOrderController@index')->name('user.orders');
        Route::get('/user/order/show/{id}/{user_id}','AdminOrderController@show')->name('user.order.show');
        // site users agents
        Route::get('/agents','AdminUserController@agentsList')->name('agents');
        Route::get('/agents/create','AdminUserController@createAgent')->name('create.agent');
        Route::get('/agents/{id}/edit','AdminUserController@editAgent')->name('edit.agent');
        Route::post('/agent/add','AdminUserController@addAgent')->name('add.agent');
        Route::post('/agent/update/{id}','AdminUserController@updateAgent')->name('update.agent');
        Route::post('password-sent','AdminUserController@passwordSent')->name('passwordSent');
        Route::get('/agents/showAgentsUser/{id}','AdminUserController@showAgentsUser')->name('agents.showAgentsUser');//xxxxxxxxxxxxxxxxxxx
        // Leads
        Route::get('/leads','AdminPolicyLeadController@index')->name('leads');
        Route::get('/leads/show/{id}','AdminPolicyLeadController@show')->name('leads.view');
        // Order
        Route::resource('/orders','AdminOrderController');
        //Route::get('/orders/{id}/edit','AdminUserController@editAgent')->name('edit.agent');
        //Route::get('/orders/show/{id}','AdminOrderController@show')->name('orders.show');
        // Import data
        Route::get('/import/car-value',  'AdminImportCarValueController@import');
        Route::post('/import/car-value', 'AdminImportCarValueController@parseImport');
        Route::get('/import/car-value/show','AdminImportCarValueController@show')->name('carValue.view');
        // Report
        Route::get('/reports/commission','AdminReportController@commission')->name('reports.commission');
        Route::get('/reports/commission/agent','AdminReportController@agentcommission')->name('reports.commission.agent');
        
        // Email template data
        Route::resource('/email-templates','AdminEmailTemplateController');
        Route::post('/email-templates/preview','AdminEmailTemplateController@preview')->name('email-templates.preview');;
        // Page/CMS
        Route::resource('/pages','AdminPageController');
        Route::any('/pages/suggest_slug','AdminPageController@suggestUniqueSlug')->name('pages.suggestSlug');

        // NEED TO CHECK
        Route::post('changehomepage','HomepageController@editHomePage')->name('editHomePage');
        //Route::resource('sites','SiteController');
        //Route::post('retrievedatathirdparty','AdminThirdPartyCoverController@getDataThirdParty');
        Route::post('retrievedatathirdparty','AdminThirdPartyCoverController@getDataThirdParty')->name('getDataThirdParty');
        Route::post('retrievedatacarpremium','AdminCarPremiumController@getDataCarPremium')->name('getDataCarPremium');
        Route::post('addplanbenefit','AdminPlanBenefitController@addFormPlanBenefit')->name('addFormPlanBenefit');
        Route::post('editplanbenefit','AdminPlanBenefitController@editFormPlanBenefit')->name('editFormPlanBenefit');

        //roles
        Route::resource('/roles', 'Auth\RoleController');
        // 
        Route::resource('/admin-users','AdminPanelUserController');

        //document master
        Route::resource('/policydocumentmaster','AdminPolicyDocumentMasterController');
        //Addon Category
        Route::resource('/addoncategory','AdminAddonCategory');
    });
});

Route::post('/paymentdata','HomeController@paymentdata');
Route::get('/paymentpage','HomeController@payment');

Route::post('/orderdata','HomeController@orderDetails')->name('order-submit');

Route::prefix('agent')->group(function() {
    Route::middleware('auth','permission:agent')->get('dashboard', 'HomeController@dashboard')->name('agent-dashboard');
    Route::middleware('auth','permission:agent')->get('dashboard/my-policy', 'HomeController@mypolicy')->name('agent-mypolicy');
    Route::middleware('auth','permission:agent')->get('dashboard/my-myprofile', 'HomeController@myprofile')->name('agent-myprofile');
    Route::middleware('auth','permission:agent')->post('/dashboard/my-profile/update','HomeController@updateprofile')->name('agent-update-profile');
    Route::middleware('auth','permission:agent')->get('dashboard/agent-commission-report', 'HomeController@agentcommissionreport')->name('agent-commission-report');
});

Route::prefix('user')->group(function() {
    Route::middleware('auth','permission:user')->get('dashboard', 'HomeController@dashboard')->name('user-dashboard');
    Route::middleware('auth','permission:user')->get('dashboard/my-policy', 'HomeController@mypolicy')->name('user-mypolicy');
    Route::middleware('auth','permission:user')->get('dashboard/my-profile', 'HomeController@myprofile')->name('user-myprofile');

    Route::middleware('auth','permission:user')->post('/dashboard/my-profile/update','HomeController@updateprofile')->name('user-update-profile');
});

Route::post('/orderdata','HomeController@orderDetails')->name('order-submit');
// Route::get('/orderdata','HomeController@orderSave');

//Route::get('/dashboard', 'UserController@dashboard');

Route::get('please-verify-email', function(){
    return view('auth.verify');
});

//buynow for policy
Route::get('/buynow','HomeController@upload');

//upload of file

resources/views/admin/email_teplates/index.blade.php
@extends('layouts.admin.master')
{{-- Ca makes table view --}}
@section('content')
<div class="row">
    <!-- error/message -->
    <div>
        @if (Session::has('error'))
            <div class="alert alert-danger">
                <a class="close" data-dismiss="alert" href="#">×</a>
                <p>{!! Session::get('error') !!}</p>
            </div>
        @endif
        @if (Session::has('success'))
             <div class="alert alert-success">
                <a class="close" data-dismiss="alert" href="#">×</a>
                <p>{!! Session::get('success') !!}</p>
             </div>
         @endif
    </div>
</div>

<!-- widget grid -->
<section id="widget-grid" class="">

    <!-- row -->
    <div class="row">

        <!-- NEW WIDGET START -->
		<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            
            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false" data-widget-sortable="false" data-widget-deletebutton="false" data-widget-togglebutton="false" data-widget-colorbutton="false">
                <!-- widget options:
                usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                data-widget-colorbutton="false"
                data-widget-editbutton="false"
                data-widget-togglebutton="false"
                data-widget-deletebutton="false"
                data-widget-fullscreenbutton="false"
                data-widget-custombutton="false"
                data-widget-collapsed="true"
                data-widget-sortable="false"

                -->
                <header>
                    <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                    <h2>{{$tableHeading ?? 'Cars'}}</h2>

                </header>
                
                <!-- widget div-->
                <div>

                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->

                    </div>
                    <!-- end widget edit box -->

                    <!-- widget content -->
                    <div class="widget-body no-padding">
                       
                        
                        <table id="dt_basic" class="table table-striped table-bordered table-hover" width="100%">
                            <thead>
                                <tr>
                                    <th>Description</th>
                                    <th>Grouping</th>
                                    <th>Subject</th>
                                    <!-- <th>Notification</th> -->
                                    <th>Code</th>
                                    <th>Status</th>
                                    <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if($emailTeplates)
                                @foreach($emailTeplates as $emailTeplate)
                                <tr>
                                    <td>{{ $emailTeplate->description }} </td>
                                    <td>{{ $emailTeplate->group_name }} </td>
                                    <td>{{ $emailTeplate->default_subject }} </td>
                                    <td>{{ $emailTeplate->code }} </td>
                                    <td> {{ $emailTeplate->status==1 ? 'Active' : 'In-active' }} </td>
                                    <td> <a class="btn btn-primary" href="{{route('admin.email-templates.edit',[$emailTeplate->id])}}">Edit</a> </td>
                                </tr>
                                @endforeach
                                @endif
                            </tbody>
                        </table>
                        
                    </div>
                    <!-- end widget content -->

                </div>
                <!-- end widget div -->

            </div>
            <!-- end widget -->

        </article>
        
    </div>

</section>

@endsection

@section('script')
<!-- PAGE RELATED PLUGIN(S) -->
<script src="{{ URL::asset('assets/admin/js/plugin/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('assets/admin/js/plugin/datatables/dataTables.colVis.min.js') }}"></script>
<script src="{{ URL::asset('assets/admin/js/plugin/datatables/dataTables.tableTools.min.js') }}"></script>
<script src="{{ URL::asset('assets/admin/js/plugin/datatables/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ URL::asset('assets/admin/js/plugin/datatable-responsive/datatables.responsive.min.js') }}"></script>
<script type="text/javascript">
		
	// DO NOT REMOVE : GLOBAL FUNCTIONS!
		
    $(document).ready(function() {
        
        pageSetUp();
        
        /* // DOM Position key index //
    
        l - Length changing (dropdown)
        f - Filtering input (search)
        t - The Table! (datatable)
        i - Information (records)
        p - Pagination (paging)
        r - pRocessing 
        < and > - div elements
        <"#id" and > - div with an id
        <"class" and > - div with a class
        <"#id.class" and > - div with an id and class
        
        Also see: http://legacy.datatables.net/usage/features
        */	

        /* BASIC ;*/
            var responsiveHelper_dt_basic = undefined;
            var responsiveHelper_datatable_fixed_column = undefined;
            var responsiveHelper_datatable_col_reorder = undefined;
            var responsiveHelper_datatable_tabletools = undefined;
            
            var breakpointDefinition = {
                tablet : 1024,
                phone : 480
            };

            $('#dt_basic').dataTable({
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
                    "t"+
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "autoWidth" : true,
                "oLanguage": {
                    "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
                },
                "preDrawCallback" : function() {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_dt_basic) {
                        responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
                    }
                },
                "rowCallback" : function(nRow) {
                    responsiveHelper_dt_basic.createExpandIcon(nRow);
                },
                "drawCallback" : function(oSettings) {
                    responsiveHelper_dt_basic.respond();
                }
            });

        /* END BASIC */
        
        // /* COLUMN FILTER  */
        // var otable = $('#datatable_fixed_column').DataTable({
        //     //"bFilter": false,
        //     //"bInfo": false,
        //     //"bLengthChange": false
        //     //"bAutoWidth": false,
        //     //"bPaginate": false,
        //     //"bStateSave": true // saves sort state using localStorage
        //     "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>"+
        //             "t"+
        //             "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
        //     "autoWidth" : true,
        //     "oLanguage": {
        //         "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
        //     },
        //     "preDrawCallback" : function() {
        //         // Initialize the responsive datatables helper once.
        //         if (!responsiveHelper_datatable_fixed_column) {
        //             responsiveHelper_datatable_fixed_column = new ResponsiveDatatablesHelper($('#datatable_fixed_column'), breakpointDefinition);
        //         }
        //     },
        //     "rowCallback" : function(nRow) {
        //         responsiveHelper_datatable_fixed_column.createExpandIcon(nRow);
        //     },
        //     "drawCallback" : function(oSettings) {
        //         responsiveHelper_datatable_fixed_column.respond();
        //     }		
        
        // });
        
        // // custom toolbar
        // $("div.toolbar").html('<div class="text-right"><img src="img/logo.png" alt="SmartAdmin" style="width: 111px; margin-top: 3px; margin-right: 10px;"></div>');
                
        // // Apply the filter
        // $("#datatable_fixed_column thead th input[type=text]").on( 'keyup change', function () {
            
        //     otable
        //         .column( $(this).parent().index()+':visible' )
        //         .search( this.value )
        //         .draw();
                
        // } );
        // /* END COLUMN FILTER */   
    
        // /* COLUMN SHOW - HIDE */
        // $('#datatable_col_reorder').dataTable({
        //     "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'C>r>"+
        //             "t"+
        //             "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
        //     "autoWidth" : true,
        //     "oLanguage": {
        //         "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
        //     },
        //     "preDrawCallback" : function() {
        //         // Initialize the responsive datatables helper once.
        //         if (!responsiveHelper_datatable_col_reorder) {
        //             responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($('#datatable_col_reorder'), breakpointDefinition);
        //         }
        //     },
        //     "rowCallback" : function(nRow) {
        //         responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
        //     },
        //     "drawCallback" : function(oSettings) {
        //         responsiveHelper_datatable_col_reorder.respond();
        //     }			
        // });
        
        // /* END COLUMN SHOW - HIDE */

        // /* TABLETOOLS */
        // $('#datatable_tabletools').dataTable({
            
        //     // Tabletools options: 
        //     //   https://datatables.net/extensions/tabletools/button_options
        //     "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
        //             "t"+
        //             "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
        //     "oLanguage": {
        //         "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
        //     },		
        //     "oTableTools": {
        //             "aButtons": [
        //             "copy",
        //             "csv",
        //             "xls",
        //             {
        //                 "sExtends": "pdf",
        //                 "sTitle": "SmartAdmin_PDF",
        //                 "sPdfMessage": "SmartAdmin PDF Export",
        //                 "sPdfSize": "letter"
        //             },
        //             {
        //                 "sExtends": "print",
        //                 "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
        //             }
        //             ],
        //         "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
        //     },
        //     "autoWidth" : true,
        //     "preDrawCallback" : function() {
        //         // Initialize the responsive datatables helper once.
        //         if (!responsiveHelper_datatable_tabletools) {
        //             responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
        //         }
        //     },
        //     "rowCallback" : function(nRow) {
        //         responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
        //     },
        //     "drawCallback" : function(oSettings) {
        //         responsiveHelper_datatable_tabletools.respond();
        //     }
        // });
        
        // /* END TABLETOOLS */
    
    })

</script>
@endsection