routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/', 'SiteController@index');
// Route::get('/contact-us', 'SiteController@contactUs')->name('contactUs');
// Route::get('/terms', 'SiteController@terms')->name('terms');
// Route::get('/privacy-policy', 'SiteController@privacyPolicy')->name('privacyPolicy');
// Route::get('/payment-refund-policy', 'SiteController@paymentRefundPolicy')->name('paymentRefundPolicy');
// Route::get('/disclaimer', 'SiteController@disclaimer')->name('disclaimer');

Auth::routes(['verify' => true]);

//Route::middleware(['verified', 'auth'])->get('/home', 'HomeController@index')->name('home');
Route::get('/start', 'HomeController@start')->name('start');
Route::any('/ajax-register', 'HomeController@createAccountAjax');
Route::post('/ajax-register-otp', 'HomeController@createAccountAjaxOTP');
Route::post('/ajax-car-makes', 'HomeController@getCarMakes')->name('ajaxGetCarMakes');
Route::post('/ajax-car-models', 'HomeController@getCarModels')->name('ajaxGetCarModels');
Route::post('/ajax-car-variants', 'HomeController@getCarVariants')->name('ajaxGetCarVariants');
Route::post('/ajax-car-values', 'HomeController@getCarValues')->name('ajaxGetCarValues');
Route::post('/ajax-save-car-leads', 'HomeController@saveCarLeads')->name('ajaxSaveCarLeads');
Route::post('/ajax-save-more-about-me', 'HomeController@saveMoreAboutMe')->name('ajaxSaveMoreAboutMe');
Route::post('/ajax-save-renewal-details', 'HomeController@saveRenewalDetails')->name('ajaxSaveRenewalDetails');
Route::post('/ajax-filter-detail', 'HomeController@getFilterResult')->name('ajaxGetFilterResult');
Route::get('/reset-password/{token}', 'UserController@resetPassword')->name('resetPassword');
Route::post('/reset-password-save','UserController@resetPasswordSave')->name('resetPasswordSave');

//premium policy page route
Route::get('/premiumplans', 'HomeController@getPremium')->name('premium');

//Route::post('ajaxGetData/{$page}','AdminCarMakeController@ajaxGetDatas');


Route::prefix('admin')->name('admin.')->group(function() {
    // Admin Auth
    Route::get('/', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login')->name('login.submit');
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('logout');
    // 
    // 
    Route::middleware(['role:super-admin|sub-admin'])->group(function () {
        //
        Route::get('/home', 'AdminController@index')->name('home');

        // Cars
        Route::post('/cars/make/models','AdminCarController@getCarMakeModels')->name('getCarMakeModels');
        Route::post('/cars/body_type/variants','AdminCarController@getVariantByBodyType')->name('getVariantByBodyType');
        // car section 
        Route::resource('/car','AdminCarController');
        Route::resource('/cars/car-makes','AdminCarMakeController');
        Route::resource('/cars/car-models','AdminCarModelController');
        Route::resource('/cars/car-model-variants','AdminCarModelVariantController');
        Route::resource('/cars/car-model-body','AdminCarModelBodyController');
        Route::resource('/cars/car-model-fuel','AdminCarModelFuelController');
        // 
        Route::post('/cars/car-body-keyword-exist','AdminCarModelBodyController@keywordExist')->name('carModelBodyKeywordExist');
        //partners 
        Route::resource('/partners/premium-plans','AdminCarPremiumController');
        Route::resource('/partners/third-party-covers','AdminThirdPartyCoverController');
        Route::resource('/partners/benefit-masters','AdminBenefitMasterController');
        Route::resource('/partners','AdminInsuranceProviderController');
        //
        Route::resource('/planbenefits','AdminPlanBenefitController');
        // 
        Route::resource('/excess','AdminExcessController');
        Route::resource('/cross-selling-products','AdminCrossSellingProductsController');
        //
        Route::resource('/homepages','HomepageController');
        // site users
        Route::resource('/users','AdminUserController');
        Route::get('/users/show/{id}','AdminUserController@show')->name('users.view');
        Route::get('/user/{user_id}/orders','AdminOrderController@index')->name('user.orders');
        Route::get('/user/order/show/{id}/{user_id}','AdminOrderController@show')->name('user.order.show');
        // site users agents
        Route::get('/agents','AdminUserController@agentsList')->name('agents');
        Route::get('/agents/create','AdminUserController@createAgent')->name('create.agent');
        Route::get('/agents/{id}/edit','AdminUserController@editAgent')->name('edit.agent');
        Route::post('/agent/add','AdminUserController@addAgent')->name('add.agent');
        Route::post('/agent/update/{id}','AdminUserController@updateAgent')->name('update.agent');
        Route::post('password-sent','AdminUserController@passwordSent')->name('passwordSent');
        Route::get('/agents/showAgentsUser/{id}','AdminUserController@showAgentsUser')->name('agents.showAgentsUser');//xxxxxxxxxxxxxxxxxxx
        // Leads
        Route::get('/leads','AdminPolicyLeadController@index')->name('leads');
        Route::get('/leads/show/{id}','AdminPolicyLeadController@show')->name('leads.view');
        // Order
        Route::resource('/orders','AdminOrderController');
        //Route::get('/orders/{id}/edit','AdminUserController@editAgent')->name('edit.agent');
        //Route::get('/orders/show/{id}','AdminOrderController@show')->name('orders.show');
        // Import data
        Route::get('/import/car-value',  'AdminImportCarValueController@import');
        Route::post('/import/car-value', 'AdminImportCarValueController@parseImport');
        Route::get('/import/car-value/show','AdminImportCarValueController@show')->name('carValue.view');
        // Report
        Route::get('/reports/commission','AdminReportController@commission')->name('reports.commission');
        Route::get('/reports/commission/agent','AdminReportController@agentcommission')->name('reports.commission.agent');
        
        // Email template data
        Route::resource('/email-templates','AdminEmailTemplateController');
        Route::post('/email-templates/preview','AdminEmailTemplateController@preview')->name('email-templates.preview');;
        // Page/CMS
        Route::resource('/pages','AdminPageController');
        Route::any('/pages/suggest_slug','AdminPageController@suggestUniqueSlug')->name('pages.suggestSlug');

        // NEED TO CHECK
        Route::post('changehomepage','HomepageController@editHomePage')->name('editHomePage');
        //Route::resource('sites','SiteController');
        //Route::post('retrievedatathirdparty','AdminThirdPartyCoverController@getDataThirdParty');
        Route::post('retrievedatathirdparty','AdminThirdPartyCoverController@getDataThirdParty')->name('getDataThirdParty');
        Route::post('retrievedatacarpremium','AdminCarPremiumController@getDataCarPremium')->name('getDataCarPremium');
        Route::post('addplanbenefit','AdminPlanBenefitController@addFormPlanBenefit')->name('addFormPlanBenefit');
        Route::post('editplanbenefit','AdminPlanBenefitController@editFormPlanBenefit')->name('editFormPlanBenefit');

        //roles
        Route::resource('/roles', 'Auth\RoleController');
        // 
        Route::resource('/admin-users','AdminPanelUserController');

        //document master
        Route::resource('/policydocumentmaster','AdminPolicyDocumentMasterController');
        //Addon Category
        Route::resource('/addoncategory','AdminAddonCategory');
    });
});

Route::post('/paymentdata','HomeController@paymentdata');
Route::get('/paymentpage','HomeController@payment');

Route::post('/orderdata','HomeController@orderDetails')->name('order-submit');

Route::prefix('agent')->group(function() {
    Route::middleware('auth','permission:agent')->get('dashboard', 'HomeController@dashboard')->name('agent-dashboard');
    Route::middleware('auth','permission:agent')->get('dashboard/my-policy', 'HomeController@mypolicy')->name('agent-mypolicy');
    Route::middleware('auth','permission:agent')->get('dashboard/my-myprofile', 'HomeController@myprofile')->name('agent-myprofile');
    Route::middleware('auth','permission:agent')->post('/dashboard/my-profile/update','HomeController@updateprofile')->name('agent-update-profile');
    Route::middleware('auth','permission:agent')->get('dashboard/agent-commission-report', 'HomeController@agentcommissionreport')->name('agent-commission-report');
});

Route::prefix('user')->group(function() {
    Route::middleware('auth','permission:user')->get('dashboard', 'HomeController@dashboard')->name('user-dashboard');
    Route::middleware('auth','permission:user')->get('dashboard/my-policy', 'HomeController@mypolicy')->name('user-mypolicy');
    Route::middleware('auth','permission:user')->get('dashboard/my-profile', 'HomeController@myprofile')->name('user-myprofile');

    Route::middleware('auth','permission:user')->post('/dashboard/my-profile/update','HomeController@updateprofile')->name('user-update-profile');
});

Route::post('/orderdata','HomeController@orderDetails')->name('order-submit');
// Route::get('/orderdata','HomeController@orderSave');

//Route::get('/dashboard', 'UserController@dashboard');

Route::get('please-verify-email', function(){
    return view('auth.verify');
});

//buynow for policy
Route::get('/buynow','HomeController@upload');

//upload of file
Route::post('/upload', 'HomeController@uploadFile');
//Route::post('/uploaddocument', 'HomeController@uploadedDocuments');

app/Models/CarModelBodyType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\CarPremium;
use App\Models\CarThirdPartyCover;
use App\Models\Excess;

class CarModelBodyType extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [

    ];

    /**
     * accounts for user
     */
    public function keyword()
    {
        return $this->hasMany('App\Models\CarModelBodyTypeKeyword', 'car_model_body_type_id', 'id');
    }

    /**
     * Scope a query to only include active makes.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('car_model_body_types.status',1);
    }

    public function carPremium()
    {
        return $this->hasMany(CarPremium::class, 'car_model_body_type_id', 'id');
    }

    public function carThirdPartyCover()
    {
        return $this->hasMany(CarThirdPartyCover::class, 'car_model_body_type_id', 'id');
    }

    public function excess()
    {
        return $this->hasMany( Excess::class, 'car_model_body_type_id', 'id');
    }

    public function carModelVariant()
    {
        return $this->hasMany('App\Models\CarModelVariant');
    }
}

resources/views/admin/car_model_bodies/create_edit.blade.php
@extends('layouts.admin.master')
{{-- Cars table view --}}
@section('content')
<div class="row">
   <div>
       @if ($errors->any())
           <div class="alert alert-danger">
               <ul>
                   @foreach ($errors->all() as $error)
                       <li>{{ $error }}</li>
                   @endforeach
               </ul>
           </div>
       @endif
   </div>
</div>
<!-- widget grid -->
<section id="widget-grid" class="">

    <!-- row -->
    <div class="row">

        <!-- NEW WIDGET START -->
		<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            
            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false" data-widget-sortable="false" data-widget-deletebutton="false" data-widget-togglebutton="false" data-widget-colorbutton="false">
                <!-- widget options:
                usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                data-widget-colorbutton="false"
                data-widget-editbutton="false"
                data-widget-togglebutton="false"
                data-widget-deletebutton="false"
                data-widget-fullscreenbutton="false"
                data-widget-custombutton="false"
                data-widget-collapsed="true"
                data-widget-sortable="false"

                -->
                <header>
                    <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                    <h2>Cars</h2>

                </header>

                
                <!-- widget div-->
                <div>

                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->

                    </div>
                    <!-- end widget edit box -->

                    <!-- widget content -->
                    <div class="widget-body">

                        <form class="form-horizontal" id="formCarModelBodyType" method="POST" @if($formType == 'edit') action="{{action('AdminCarModelBodyController@update', $data->id)}}" @else action="{{url('/admin/cars/car-model-body')}}" @endif>
                             @csrf
                             @if($formType == 'edit')
                                <input name="_method" type="hidden" value="PATCH">
                            @endif
                            <fieldset>
                                <legend>{{$formTitle ?? ' '}}</legend>
                                {{--  --}}
                                <div class="form-group">
                                    <label class="control-label col-md-2">{{ $formType == 'edit' ? 'Update' : 'Enter'}} Car Body Name</label>
                                    <div class="col-md-10">
                                        <div class="row">
                                            <div class="col-sm-12">
                                                {{-- ui-autocomplete-loading --}}
                                            <input class="form-control " placeholder="e.g. Sedan" name="name" id="carModelBodyTypeName" type="text" value="{{ $errors->any() ? old('name') : $data->name ?? '' }}">

                                            <span class="my-error" style='color:#b94a48;display:none' >*</span>

                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Status</label>
                                    <div class="col-md-10">
                                        <div class="row">
                                            <div class="col-sm-2">
                                                @if($formType == 'edit') 
                                                    <select name="status" class="form-control" >
                                                        <?php $statusArry = array( 0  => 'Inactive' , 1 => 'Active' ); ?>
                                                        @foreach($statusArry as $key => $value)
                                                            @if($key == $data->status) 
                                                                <option class="form-control"  selected  value="{{ $key }}" > {{ $value }}</option>
                                                            @else
                                                                <option class="form-control" value="{{ $key }}" > {{ $value }}</option>
                                                            @endif
                                                        @endforeach
                                                    </select>
                                                @else
                                                    <select name="status" class="form-control" >
                                                        <option  class="form-control" value="0"
                                                            @if(old('status') == 0) 
                                                                {{ 'selected' }} 
                                                            @endif
                                                        >Inactive</option>

                                                        <option  class="form-control" value="1"
                                                            @if(old('status') == 1) 
                                                                {{ 'selected' }} 
                                                            @endif
                                                        >Active</option>
                                                    </select>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                {{--  --}}
                                {{-- <div class="form-group">
                                    <label class="col-md-2 control-label">Car Modal Description</label>
                                    <div class="col-md-10">
                                        <textarea class="form-control" name="carModalDescription" placeholder="Car Modal Description" rows="4"></textarea>
                                    </div>
                                </div> --}}
                            
                            </fieldset>
                            {{-- Keywords  --}}
                            <fieldset>
                                <legend>Keywords</legend>
                                {{--  --}}
                                <div id="keywordAddMoreSection">
                                    {{-- Existing --}}
                                    @if(isset($data->keyword))
                                    @php $keywords = $data->keyword @endphp
                                        @foreach($keywords as $keyword)
                                        <div class="form-group" >
                                            <label class="control-label col-md-2">Name</label>
                                            <div class="col-md-10">
                                                <div class="row">
                                                    <div class="col-sm-12">
                                                        {{-- ui-autocomplete-loading --}}
                                                    <input class="form-control keywordText" placeholder="Keyword" name="keyword[]" id="keyword" type="text" value="{{$keyword->keyword}}">
        
                                                    </div>
                                                </div>
                                                <span class="help-block hide">Keyword already exist</span>
                                            </div>
                                        </div>
                                        @endforeach
                                    @endif
                                    <div id="keywordAddBlock">
                                        <div class="form-group" >
                                            <label class="control-label col-md-2">Name</label>
                                            <div class="col-md-10">
                                                <div class="row">
                                                    <div class="col-sm-12">
                                                        {{-- ui-autocomplete-loading --}}
                                                    <input class="form-control keywordText" placeholder="Keyword" name="keyword[]" id="keyword" type="text" value="">
        
                                                    </div>
                                                </div>
                                                <span class="help-block hide">Keyword already exist</span>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Add More</label>
                                    <div class="col-md-10">
                                        <div class="row">
                                            <div class="col-sm-2">
                                                <button type="button" id="addMoreKeyword"><i class="fa fa-plus-square"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            
                            </fieldset>

                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-12">
                                        <a href="{{url('/admin/cars/car-model-body')}}" class="btn btn-default">Cancel</a>
                                        <button class="btn btn-primary" type="submit">
                                            <i class="fa fa-save"></i>
                                            {{ $formType == 'edit' ? 'Update' : 'Submit'}}
                                        </button>
                                    </div>
                                </div>
                            </div>

                        </form>

                    </div>
                    <!-- end widget content -->

                </div>
                <!-- end widget div -->

            </div>
            <!-- end widget -->

        </article>
        
    </div>

</section>

@endsection

@section('script')
<!-- PAGE RELATED PLUGIN(S) -->

<script type="text/javascript">
		
    $(document).ready(function() {

        pageSetUp();

        $("#formCarModelBodyType").on('submit',(function(e) {

            var is_valid =  validForm();
            
            if(is_valid == false){
                $(window).scrollTop(0);
                return false;
            }

        }));

        $("#addMoreKeyword").click(function() {
            var newHtml = $("#keywordAddBlock");
            newHtml.find('.form-group').removeClass('has-warning')
            newHtml.find('.help-block').addClass('hide');
            $("#keywordAddMoreSection").append(newHtml.html());
        });
         $("#keywordAddMoreSection").on('blur', '.keywordText', function() {
            var keyword = $.trim($(this).val());
            // $(this).parents('.form-group').addClass('has-error');
            if( keyword == '' ) {

            } else {
                // check if keyworkd already exist
                var bodyId = '{{$data->id ?? 0}}'
                $(this).parents('.form-group').removeClass('has-warning')
                        .find('.help-block').addClass('hide');
                $.ajax({
                type:'POST',
                url:'{{route('admin.carModelBodyKeywordExist')}}',
                context: this,
                data:{bodyId:bodyId, name:keyword },

                success:function(data){
                    if( data.action == '0' ) {
                        $(this).parents('.form-group')
                        .addClass('has-warning')
                        .find('.help-block').removeClass('hide');
                    }
                }
            });
            }
        });
    })

</script>

<script type="text/javascript">

    function validForm(){
        hideErrorDiv();

        var is_valid = true;

        var carModelBodyTypeName  = $.trim($("#carModelBodyTypeName").val());        

        if (carModelBodyTypeName == ''){
            $("#carModelBodyTypeName").parent().find(".my-error").html('Please enter Car Body Name').show();
            $('#carModelBodyTypeName').closest('.form-group').addClass('has-error');
            is_valid = false;
        }

        return is_valid;
    }
    
    function hideErrorDiv() {

        $(".my-error").hide();
        $(".form-group").removeClass('has-error');
    }
</script>
@endsection